const COUNTRY_NAMES = [
  { label: "アメリカ合衆国", value: "USA" },
  { label: "韓国", value: "Korea, South" },
  { label: "中国北部", value: "China North" },
  { label: "中国南部", value: "China South" },
  { label: "香港", value: "Hong Kong" },
  { label: "マカオ", value: "Macau" },
  { label: "台湾", value: "Taiwan" },
  { label: "インドネシア", value: "Indonesia" },
  { label: "マレーシア", value: "Malaysia" },
  { label: "フィリピン", value: "Philippines" },
  { label: "シンガポール", value: "Singapore" },
  { label: "タイ", value: "Thailand" },
  { label: "ベトナム", value: "Vietnam" },
  { label: "カンボジア", value: "Cambodia" },
  { label: "ラオス", value: "Laos" },
  { label: "ブルネイ", value: "Brunei" },
  { label: "モルディブ", value: "Maldives" },
  { label: "インド", value: "India" },
  { label: "パキスタン", value: "Pakistan" },
  { label: "オーストラリア", value: "Australia" },
  { label: "ニュージーランド", value: "New Zealand" },
  { label: "カナダ", value: "Canada" },
  { label: "メキシコ", value: "Mexico" },
  { label: "プエルトリコ", value: "Puerto Rico" },
  { label: "アルゼンチン", value: "Argentina" },
  { label: "ブラジル", value: "Brazil" },
  { label: "フランス", value: "France" },
  { label: "ドイツ", value: "Germany" },
  { label: "イタリア", value: "Italy" },
  { label: "スペイン", value: "Spain" },
  { label: "オランダ", value: "Netherlands" },
  { label: "オーストリア", value: "Austria" },
  { label: "ポーランド", value: "Poland" },
  { label: "ギリシャ", value: "Greece" },
  { label: "スウェーデン", value: "Sweden" },
  { label: "スイス", value: "Switzerland" },
  { label: "デンマーク", value: "Denmark" },
  { label: "イギリス", value: "UK" },
  { label: "サウジアラビア", value: "Saudi Arabia" },
  { label: "アラブ首長国連邦", value: "UAE" },
  { label: "ヨルダン", value: "Jordan" },
  { label: "エジプト", value: "Egypt" },
  { label: "トルコ", value: "Turkey" },
  { label: "ケニア", value: "Kenya" },
  { label: "南アフリカ", value: "South Africa" },
  { label: "ジンバブエ", value: "Zimbabwe" },
  { label: "その他", value: "Other" },
];
